#import "lib/mechanic.js"
#import "lib/tuneup/tuneup.js"
#import "config.js"

//Demo
//#import "smoke/checkout.js"
//#import "smoke/search.js"
//#import "smoke/myaccount.js"
//#import "smoke/discovery.js"
//#import "smoke/shopping.js"

//smoke
//#import "smoke/category.js"
//#import "smoke/tabbar.js"
//#import "smoke/sidebar.js"
//#import "smoke/favoriteStore.js"
//#import "smoke/favoriteItem.js"
//#import "smoke/welcome.js"
//#import "smoke/shopping.js"
//#import "smoke/itempage.js"
//#import "smoke/storeListings.js"
//#import "smoke/shoppingCartlist.js"

//functional.
//#import "Function/welcome.js"
//#import "Function/Category.js"
//#import "Function/Search.js"
//#import "Function/SRP.js"
//#import "Function/shoppingCart.js"
//#import "Function/RecentHistory.js"
//#import "Function/FavoriteItem.js"
//#import "Function/FavoriteStores.js"
#import "Function/StorePage.js"
#import "Function/MyAccount.js"
#import "Function/ItemPage.js"
#import "Function/TabBar.js"